env:
  es6: true
  node: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-non-null-assertion': 'off'

